version: '3.9'
services:
  app:
    image: balbi-be:1.0
    restart: always
    tty: true
    volumes:
      - ./:/go/src 
    ports:
      - 2000:2000
    build:
      context: .
      dockerfile: Dockerfile
      